export const DEFAULT_WATCHLIST: string[] = [
  'BTCUSDT', 'ETHUSDT', 'SOLUSDT', 'BNBUSDT', 'XRPUSDT',
  'DOGEUSDT', 'ADAUSDT', 'AVAXUSDT', 'LINKUSDT', 'DOTUSDT',
  'TRXUSDT', 'LTCUSDT', 'ATOMUSDT', 'UNIUSDT', 'INJUSDT',
]

export const STATIC_PAIRS: string[] = [
  'BTC/USDT', 'ETH/USDT', 'BNB/USDT', 'SOL/USDT', 'LTC/USDT',
  'BCH/USDT', 'AVAX/USDT', 'LINK/USDT', 'DOT/USDT', 'ATOM/USDT',
  'INJ/USDT', 'NEAR/USDT', 'APT/USDT', 'OP/USDT', 'ARB/USDT',
  'SUI/USDT', 'TIA/USDT', 'SEI/USDT', 'RUNE/USDT', 'TAO/USDT',
  'WLD/USDT', 'RNDR/USDT', 'FET/USDT', 'AAVE/USDT', 'MKR/USDT',
  'UNI/USDT', 'CRV/USDT', 'LDO/USDT', 'PENDLE/USDT', 'GMX/USDT',
  'DYDX/USDT', 'JUP/USDT', 'PYTH/USDT', 'ENA/USDT', 'ONDO/USDT',
  'EIGEN/USDT', 'ETHFI/USDT', 'HYPE/USDT', 'BERA/USDT', 'STX/USDT',
  'XRP/USDT', 'ADA/USDT', 'DOGE/USDT', 'TRX/USDT', 'XLM/USDT',
  'HBAR/USDT', 'VET/USDT', 'EGLD/USDT', 'FIL/USDT', 'ICP/USDT',
  'THETA/USDT', 'FLOW/USDT', 'ALGO/USDT', 'SAND/USDT', 'MANA/USDT',
  'AXS/USDT', 'IMX/USDT', 'GALA/USDT', 'APE/USDT', 'GRT/USDT',
  'WIF/USDT', 'PEPE/USDT', 'SHIB/USDT', 'FLOKI/USDT', 'BONK/USDT',
  'TRUMP/USDT', 'TON/USDT', 'NOT/USDT', 'ORDI/USDT', 'BLUR/USDT',
]
